#!/usr/bin/env python3
"""Generate firmware/components/web/include/web_html.h from firmware/web_ui.html.

Runs as a PlatformIO pre-build script (extra_scripts).  Converts the readable
single-file page into a C string literal embedded into the firmware (rodata).

Minification rules (safe subset):
  * HTML comments are removed.
  * Newlines are collapsed to a single space.  This keeps token separation in
    JS/CSS (e.g. "div\nspan" -> "div span"), so the SOURCE must not contain:
      - "//" line comments,
      - backtick template literals spanning multiple lines,
      - double spaces inside string literals.
  * Whitespace between tags (">\\s+<") and repeated whitespace are collapsed.

The header is only rewritten when the content actually changes, so CMake does
not recompile web.c on every build.
"""

import os
import re
import sys

if "__file__" in globals():
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
else:
    # PlatformIO runs extra scripts via SConscript without __file__;
    # cwd is the project directory (the one containing platformio.ini).
    ROOT = os.getcwd()
SRC = os.path.join(ROOT, "web_ui.html")
OUT = os.path.join(ROOT, "components", "web", "include", "web_html.h")
VERSION_FILE = os.path.join(ROOT, "version.txt")

CHUNK = 1024


def read_version():
    """Current firmware version; single source of truth is version.txt."""
    try:
        with open(VERSION_FILE, "r", encoding="utf-8") as f:
            v = f.read().strip()
        return v if v else "0.0"
    except OSError:
        return "0.0"


def minify(html):
    html = re.sub(r"<!--.*?-->", "", html, flags=re.S)
    html = html.replace("\r\n", "\n").replace("\r", "\n")
    html = re.sub(r">\s+<", "><", html)
    html = re.sub(r"\n[ \t]*", " ", html)
    html = re.sub(r"\s{2,}", " ", html)
    return html.strip()


def split_chunks(escaped, size):
    chunks = []
    i = 0
    n = len(escaped)
    while i < n:
        end = min(i + size, n)
        if end < n and escaped[end - 1] == "\\":
            end += 1  # do not split an escape sequence across chunks
        chunks.append(escaped[i:end])
        i = end
    return chunks


def build_header(body, version):
    escaped = body.replace("\\", "\\\\").replace('"', '\\"')
    lines = [
        "/* Generated by tools/gen_web_html.py from web_ui.html - DO NOT EDIT. */",
        "#ifndef WEB_HTML_H",
        "#define WEB_HTML_H",
        "",
        "/* Firmware version (single source of truth: version.txt). */",
        '#define WEB_FW_VERSION "' + version + '"',
        "",
        "static const char s_page_html[] =",
    ]
    for chunk in split_chunks(escaped, CHUNK):
        lines.append('    "' + chunk + '"')
    lines.append("    ;")
    lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    if not os.path.isfile(SRC):
        print("gen_web_html: ERROR source %s not found" % SRC)
        return 1
    with open(SRC, "r", encoding="utf-8") as f:
        body = minify(f.read())
    version = read_version()
    body = body.replace("__VERSION__", version)
    out = build_header(body, version)
    try:
        with open(OUT, "r", encoding="utf-8") as f:
            if f.read() == out:
                print("gen_web_html: up to date (%d bytes page)" % len(body))
                return 0
    except OSError:
        pass
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print("gen_web_html: wrote %s (%d bytes page, %.1f KB)" %
          (OUT, len(body), len(body) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
else:
    # Run as a PlatformIO extra script (exec'd by SCons, __name__ != "__main__"):
    # call main() without sys.exit so the build process is not terminated.
    main()
