#!/usr/bin/env python3
"""Embed the prebuilt, offline sound editor without rewriting JavaScript."""

import argparse
import gzip
import hashlib
import json
from pathlib import Path
import re


MIME = {".html": "text/html; charset=utf-8", ".js": "application/javascript",
        ".css": "text/css", ".txt": "text/plain; charset=utf-8",
        ".json": "application/json", ".svg": "image/svg+xml"}


def verify_sources(dist, source):
    source = Path(source)
    stamp = Path(dist) / "build-inputs.json"
    if not stamp.is_file():
        raise ValueError("Editor source stamp missing: run npm run build in firmware/sound_editor")
    recorded = json.loads(stamp.read_text(encoding="utf-8"))
    paths = [source / name for name in ("index.html", "package.json", "package-lock.json",
                                       "tsconfig.json", "vite.config.ts")]
    for directory in ("src", "scripts", "public"):
        paths.extend(path for path in (source / directory).rglob("*") if path.is_file())
    expected = {path.relative_to(source).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
                for path in paths}
    if recorded.get("files") != expected:
        raise ValueError("Editor source changed after build: run npm run build in firmware/sound_editor")


def generate(dist, output, source=None):
    dist, output = Path(dist), Path(output)
    if not (dist / "index.html").is_file():
        raise ValueError("Editor build missing: run npm ci and npm run build in firmware/sound_editor")
    if not output.is_dir():
        raise ValueError("Generated asset output directory does not exist")
    if source is not None:
        verify_sources(dist, source)
    files = sorted(path for path in dist.rglob("*") if path.is_file()
                   and path.suffix != ".gz"
                   and path.name not in {"asset-sizes.json", "bundled-packages.json", "build-inputs.json"})
    if len(files) > 32:
        raise ValueError("Too many editor assets (maximum 32)")
    lines = ['/* Generated by tools/gen_sound_editor.py. Do not edit. */',
             '#include "sound_editor_assets.h"', '']
    entries, sizes = [], []
    for index, path in enumerate(files):
        relative = path.relative_to(dist).as_posix()
        if path.is_symlink() or not re.fullmatch(r"[A-Za-z0-9_./-]+", relative):
            raise ValueError("Unsafe editor asset name")
        if path.suffix not in MIME:
            raise ValueError("Unsupported editor asset: " + relative)
        raw = path.read_bytes()
        data = gzip.compress(raw, compresslevel=9, mtime=0)
        name = "editor_asset_" + str(index)
        lines.append("static const unsigned char " + name + "[] = {")
        for offset in range(0, len(data), 24):
            lines.append("    " + ",".join(str(byte) for byte in data[offset:offset + 24]) + ",")
        lines.append("};")
        immutable = "true" if relative.startswith("assets/") else "false"
        entries.append('    {"/sound-editor/' + relative + '", "' + MIME[path.suffix]
                       + '", ' + name + ', sizeof(' + name + '), ' + immutable + '},')
        sizes.append({"path": relative, "bytes": len(raw), "gzipBytes": len(data),
                      "sha256": hashlib.sha256(raw).hexdigest()})
    total = sum(item["gzipBytes"] for item in sizes)
    if total > 512 * 1024:
        raise ValueError("Editor compressed assets exceed the 512 KiB resource budget")
    lines.extend(['', 'const sound_editor_asset_t sound_editor_assets[] = {', *entries, '};',
                  'const size_t sound_editor_asset_count = sizeof(sound_editor_assets) / sizeof(sound_editor_assets[0]);', ''])
    target = output / "sound_editor_assets.c"
    text = "\n".join(lines)
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        target.write_text(text, encoding="utf-8", newline="\n")
    print(json.dumps({"assets": sizes, "totalGzipBytes": total}, indent=2))
    return total


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--dist", type=Path, default=root / "sound_editor" / "dist")
    parser.add_argument("--source", type=Path, default=root / "sound_editor")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        generate(args.dist, args.output, args.source)
    except (OSError, ValueError) as error:
        parser.exit(1, "sound editor assets: " + str(error) + "\n")
