[platformio]
src_dir = main

[env:esp32-s3-devkitc-1]
platform = espressif32
framework = espidf
board = esp32-s3-devkitc-1
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = pre:tools/gen_web_html.py
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

[env:test_native]
platform = native
test_framework = unity
build_src_filter = -<*>
build_flags =
    -Itest_libs/teststubs/include
    -Icomponents/dcc/include
    -Icomponents/pinmap/include
    -Icomponents/settings/include

